### ISSUE TITLE
Table information not populated in UpdateColumn function.

### ISSUE THREAD

**Issue by jthope** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#182]
In the UpdateColumn function (.tt file), both Column and Table objects are handed in. But it appears the table object isn't fully populated at this time. I am renaming the primary key only if the table has one primary key defined, otherwise I want to ignore. My thought was to check the count of the PrimaryKeys property, however it is empty. A simple example:

```c#
if (!table.IsView && table.PrimaryKeys.Count() == 1)
{
    if (column.IsPrimaryKey) 
         column.NameHumanCase = "Id";
}
```

Is there another way I can check in the UpdateColumn function if the current table has multiple primary keys?

Thanks

**Comment by sjh37** [comment]
Don't try this as could be problematic:

```c#
table.SetPrimaryKeys();
if (!table.IsView && table.PrimaryKeys.Count() == 1 && column.IsPrimaryKey)
    column.NameHumanCase = "Id";
```

Because there could be other columns not yet imported which could also be primary keys.

`UpdateColumn` is called as each column is added to the table, not when all columns have already been added. Although this could be changed.

Try this instead:
- In the file `EF.Reverse.POCO.Core.ttinclude` approx line 2795, remove `col = updateColumn(col, table);`
- At line 2186, just before the comment `// Check for property name clashes in columns`, add the following:
```c#
foreach (Table t in result)
{
    t.SetPrimaryKeys();
    t.Columns.ForEach(c => c.NameHumanCase = updateColumn(c, t).NameHumanCase);
}
```

Let me know if that works for you

**Comment by jthope** [comment]
Looks like that did the trick! Thank you!
