### ISSUE TITLE
set "DbContextInterfaceName"  to null o empty

### ISSUE THREAD

**Issue by piqm** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#184]
I need my file context does not implement any interface.

![image](https://cloud.githubusercontent.com/assets/1207399/21836034/ec86d4fe-d78f-11e6-9501-c7ccce707ebd.png)

![image](https://cloud.githubusercontent.com/assets/1207399/21836040/f7a981d8-d78f-11e6-93ab-5f294170265c.png)

**Comment by sjh37** [comment]
If you don't use an interface, how else are you going to unit test your business logic?
The simple answer is you can't. In order to test the business logic, you pass in a fake db context to your business logic, if you don't code against an interface you can't do that. So it sounds like you are wanting to code against the concrete class, which is bad programming practice.

For best coding practice, always code against an interface. Read up on SOLID and about the "Dependency Inversion Principle". Here are a couple of links.

- http://williamdurand.fr/2013/07/30/from-stupid-to-solid-code/
- https://code.tutsplus.com/tutorials/solid-part-4-the-dependency-inversion-principle--net-36872

If you want to go ahead and code against the concrete class, then do so. Just because there is an interface generated should not cause you any problems.

**Comment by piqm** [comment]
I use an interface but in a partial class but I want it in my class generated by the tool does not implement it.

**Comment by sjh37** [comment]
ok. in that case modify `EF.Reverse.POCO.ttinclude` approx line 212 and change
```c#
public <# if(MakeClassesPartial) { #>partial <# } #>class <#=DbContextName#> : <#=DbContextBaseClass#>, <#=DbContextInterfaceName#>
```
to
```c#
public <# if(MakeClassesPartial) { #>partial <# } #>class <#=DbContextName#> : <#=DbContextBaseClass#>
```

If you are using fakes, you will have to remove `<#=DbContextInterfaceName#>` from there too, line 507.
