### ISSUE TITLE
Columns with default value should not get IsRequired()

### ISSUE THREAD

**Issue by mohaaron** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#346]
I have table column which has a default('') value and the generator is still adding a IsRequired attribute to the field. I want IsRequired to not get added to fields that specify NOT NULL DEFAULT(???). Is this possible. I'm looking through the EF.Reverse.POCO.Core.ttinclude but don't understand it will enough to work out a solution.

**Comment by sjh37** [comment]
Hi @mohaaron.
The constructor of the poco table should contain the default value for it.
If you pass in null, it will attempt to update that record with null. Defaults kick in when the column is omitted from the insert, otherwise it takes what you have.
Entity Framework will always pass in all fields to the insert, and therefore you have to supply the default, and not the database.
If you are to never use this column, then go ahead and mark that column hidden inside UpdateColumn() callback. EF will no nothing about that field, and any inserts will work because of the default value.

Apparently EF 7 will have better support for default values. For now, you either have to exclude the column (set hidden=true for it), or supply a default for it. The default is automatically supplied by the generator via the constructor of the poco.
