### ISSUE TITLE
trust Level

### ISSUE THREAD

**Issue by smarteez17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#370]
Hi, can you advise what trust level you using?

is the option for medium  trust level

**Comment by sjh37** [comment]
Your question is very vague, and I'm not sure what you are asking.

Are talking about the web.config for your ASP.NET application? For example:
```xml
<system.web>
  <securityPolicy>
    <trustLevel name="Full" policyFile="internal"/>
  </securityPolicy>
</system.web>
```
If so, I don't use it, and it has nothing to do with this project.

Or are you talking about what SQL Server security is required in order to successfully reverse engineer the database?

**Comment by smarteez17** [comment]
Hi there 
sorry about this 

I need to have medium trust level only 

And I am trying to find what using full , and i was checking  if it was poco

**Comment by sjh37** [comment]
No problem. It has nothing to do with the reverse poco generator.
This project generates mapping code, and has nothing to do with ASP.NET trust levels.
