### ISSUE TITLE
Workaround tables without primary keys

### ISSUE THREAD

**Issue by ClassyCircuit** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#384]
Hi,
I have to modify a lot of tables, which are missing primary keys, but I do not have permission to modify the model of the database, so I am looking for a work-around to use these tables with entity framework.
Is it somehow possible to force EF to allow using these tables, or at least manually let me specify, which column *might* be unique?

Right now this tool generates these classes with comments:

> // The table 'Test_Table' is not usable by entity framework because it
> // does not have a primary key. It is listed here for completeness

I completely understand the implications of using tables w/o primary keys, but I have no control over the database design, I am merely using it.

Thank you

**Comment by sjh37** [comment]
Hi. The generator automatically assigns primary keys to tables with no primary keys by setting all NOT NULL columns as primary keys. See `Table.SetPrimaryKeys()`
The tables listed as 'not usable...' therefore must have all NULLable columns.

You could try and set the primary key yourself by using UpdateColumn() function in your settings.tt file:

```c#
Settings.UpdateColumn = (Column column, Table table) =>
{
    if(!table.HasPrimaryKey)
    {
        // This table is not allowed in EntityFramework as it does not have a primary key.
        // Therefore generate a composite key from all fields.
        foreach(var col in table.Columns.Where(x => !x.Hidden))
        {
            col.IsPrimaryKey = true;
            col.IsNullable = false; // Primary keys are not allowed to be NULL
            table.HasPrimaryKey = true;
        }
    }
    ....
}
```

If you know which tables and which columns to force to be a primary key, then you can perform that here instead of the foreach loop.

**Comment by ClassyCircuit** [comment]
Thank you, that helped me.
