### ISSUE TITLE
Generate Invalid Return Models

### ISSUE THREAD

**Issue by roughiain** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#48]
Currently the following is being generated:

 public System.Decimal? 01To30Days { get; set; }
        public System.Decimal? 31To60Days { get; set; }
        public System.Decimal? 61To90Days { get; set; }
        public System.Decimal? 91To120Days { get; set; }
        public System.Decimal? 120PlusDays { get; set; }

Would also be nice to have a update column function for the return models

**Comment by sjh37** [comment]
Hi, Unfortunately I am not allowed to modify the return models from stored procedures, otherwise the `Database.SqlQuery<YourReturnModel>("EXEC ...")` won't map correctly.
The only thing I can do here is to detect invalid C# return models and prevent the stored proc being generated, however you can do that via the `StoredProcedureFilterExclude` regex.

If you need to use that stored proc, then you still have to exclude it as above, but create a new stored procedure to call this one, and change the result set to be To30Days, To60Days, etc.
