### ISSUE TITLE
settings.namespace vs Settings.PocoConfigurationNamespace

### ISSUE THREAD

**Issue by nlnpraveen** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#502]
I am on version 2.37.4.0.
I went through the PluralSight course.
Which setting overrides the other? In my case it doesn't seem to respect the value set in Settings.PocoConfigurationNamespace.

It doesn't generate without providing a value for settings.namespace. Is there a way I can only set Settings.PocoConfigurationNamespace and get the namespaces working? I have set this as well:

Settings.ElementsToGenerate = Elements.PocoConfiguration;

Regardless of what I set on Settings.PocoConfigurationNamespace, it always uses the Settings.Namespace value. Am I missing something?

Regards,
Praveen

**Comment by sjh37** [comment]
Hi @nlnpraveen 
`Settings.PocoConfigurationNamespace` adds a `using` statement to the C# code, the value of which is the contents of Settings.PocoConfigurationNamespace.
The namespace the code is generated inside is always `Settings.Namespace`.

`Settings.PocoConfigurationNamespace` comes into play when you generate different ElementsToGenerate in different folders. Those folders have namespaces.

So for example, if your root namespace is 'Demo'
```c#
Settings.ElementsToGenerate = Elements.PocoConfiguration;
```
in a folder named "Config", will generate code with a namespace of "Demo.Config".
The code will have errors, because it won't know which namespace the dbcontext resides. Therefore you tell it to use the namespace where the dbcontext is, this is done via the
```c#
Settings.ContextNamespace = "Demo.Context";
```
which adds a `using Demo.Context;` to your generated code.

So simply fill in the namespaces where the code got generated, and fill in:
```c#
Settings.PocoNamespace = "Demo.Entity";
Settings.ContextNamespace = "Demo.Context";
Settings.UnitOfWorkNamespace = "Demo.Context";
Settings.PocoConfigurationNamespace = "Demo.Config";
```

So above, there would be 3 folders, 'Entity', 'Context' and 'Config'.
Entity for just the Poco classes.
Context for both the dbcontext and db context interface.
Config for the configuration classes.

Just to be clear, the code is generated in the Settings.Namespace namespace, the 
```c#
Settings.PocoNamespace = "Demo.Entity";
Settings.ContextNamespace = "Demo.Context";
Settings.UnitOfWorkNamespace = "Demo.Context";
Settings.PocoConfigurationNamespace = "Demo.Config";
```
Adds a `using` statement to the generated code for the bits of code that it needs to reference.

Does that anwer your question?

**Comment by sjh37** [comment]
Let me know if you still need help, or re-watch the course, module `Organizing the Generated Code` section `Demo: Separating Generated Code into Folders`

[Link here to the course section you need](https://app.pluralsight.com/player?course=code-first-entity-framework-legacy-databases&author=simon-hughes&name=code-first-entity-framework-legacy-databases-m4&clip=4&mode=live)

**Comment by nlnpraveen** [comment]
Thanks Simon. I now understand the purpose of the namespace settings of POCO, Context, UnitOfWork and Configuration. It is to add the using statement appropriately. I think now my problem is this:

Settings.Namespace = "Demo";
Settings.ElementsToGenerate = Elements.Poco;

My tt file resides in an Entities folder (the core files reside outside). Though the POCOs are generated in that folder, it does not generate the POCOs in the namespace Demo.Entities. It generates them within the Demo namespace only. Any ideas why?

**Comment by sjh37** [comment]
It should do it correctly, however as it's not in your case, try using
```c# 
Settings.Namespace = "Demo.Entities";
```

**Comment by nlnpraveen** [comment]
Thanks Simon. That worked!
