### ISSUE TITLE
Fake DbContext doesn't inherit from DbContext like 'real' one does

### ISSUE THREAD

**Issue by CmdrBeavis** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#51]
One of my unit tests is failing due to the following exception;

> System.InvalidCastException: Unable to cast object of type 'MyWebAPI.Data.FakeMyWebApiDbContext' to type 'System.Data.Entity.DbContext'..

Which lead me to notice that the Fake doesn't inherit from DbContext like the real one does. e.g.

[System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
public class MyWebApiDbContext : **System.Data.Entity.DbContext,** IMyWebApiDbContext

[System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
public class FakeMyWebApiDbContext : IMyWebApiDbContext

**Comment by kkman021** [comment]
All i have try,that is not the real DbContext,
It's just like linq to object. 
You can find some detail in FakeDbSet.
So, there has some limit which you like to write something with unit test.

If you really want to test the code
I guest the best way is Integration Testing, 
Test the code with a real DB .

It's just my suggestion, if there's a better way , please let me know thanks.

**Comment by sjh37** [comment]
As kkman021 suggested, unit tests will be link to objects, hence there is no need to inherit from DbContext. Otherwise you end up testing entity framework,
To test against a real database, use integration tests.

You should not be casting to DbContext, but instead your business logic should be coding against the interface IMyWebApiDbContext. 
[SOLID - Interface segregation principle](https://en.wikipedia.org/wiki/Interface_segregation_principle)

**Comment by CmdrBeavis** [comment]
Well, the reason I'm casting to DbContext is the generic repository pattern
my stuff runs though. I mean, I hear what you're saying... hmmm, guess I'll
have to take another look at my code and see if I can work around this.

Thanks!

**Comment by sjh37** [comment]
No problem.
