### ISSUE TITLE
Selecting into variables and temp tables included in stored proc return models

### ISSUE THREAD

**Issue by stimpy77** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#525]
Using v2.37.4

We have a number of stored procs each with a number of processing statements like `SELECT @Variable = FieldName` or `INSERT INTO @InMemoryTable SELECT A,B` that would *not output* any result sets to the client connection, yet these are showing up in the generated stored procedure return models as return model nested properties ResultSet1, ResultSet2, etc. It would be nice if we could turn these off, or if it was smart enough to observe what would actually be exposed to the client connection as result sets and isolate just to those. 

We'd consider putting up with it, but the main issue is that, while we obviously can't use anything except what actually does emit to the client connection, we'd have to constantly be syncing the suffix number of the last property, i.e. "4" in "ResultSet4", as the stored procedure changes, even when in fact the actual stored procedure output never actually changes, only its internal processing changes.

Meanwhile is there anything we can pepper into the stored procedure itself to clue the generator to ignore the internal processing statements, like including @HEY_GENERATOR_IGNORE_THIS=1 in the select? :) Seems like this might be an easy way to generate a workaround until it's smarter about internal statements in the first place.

**Comment by stimpy77** [comment]
misidentified and misunderstood the generated output, might reopen a new, more accurate request later, something along the lines of finding a way to name the outputs rather than suffixing 1,2,3.

**Comment by sjh37** [comment]
Hi @stimpy77 Jon,
At the moment there is no way to name the ResultSet_n_ names, but it's a good suggestion, so yes please raise this as a separate case.

With regard to ResultSets, it's SQL Server that informs me that it will return _n_ result sets, each with their own result set model. In a lot of cases, SQL Server will only return one result set, however you sometimes get back several result sets when it's called with `SET FMTONLY ON;` (to obtain the result set model(s)). This usually happens when there are a few SELECT statements and SELECTs from #temp tables within the stored procedure.

You can either leave it like this, or wrap the stored procedure with an outer stored procedure which calls the inner stored procedure, and you only call the outer stored procedure. You can filter out the inner stored procedure so it's excluded and therefore the inner stored proc not callable in the EF db context.
