### ISSUE TITLE
Add Template version number to generated code comments

### ISSUE THREAD

**Issue by brianrutter** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#576]
Would it be possible to add the template version number that was used in the Generated code as a comment?

ex. 
// This code was generated by EntityFramework Reverse POCO Generator...
// v3.1.0

**Comment by sjh37** [comment]
Good idea thanks.

**Comment by sjh37** [comment]
Done, and controlled via a new setting `Settings.IncludeCodeGeneratedAttribute`.
Default for this is `false`, so users don't get diffs in GIT for every file when they use a new generator version. That would be hard to immediately track down changes to code if every file changed due to having a version number change.
This will be in the next version.

**Comment by sjh37** [comment]
Now released as part of v3.2.0
