### ISSUE TITLE
A way to only use ConnectionString Name (from app.config) ?

### ISSUE THREAD

**Issue by tss56** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#597]
Hi, I was trying to make my .tt works only with a connection string name, commenting the ConnectionString Setting itself since I want my .tt file to run on the DB defined in my app.config.
I don't want to have to re-implement it in the .tt every time I change my DB access
Thus I was wondering is there a way to only use the name and not the connectionString itself in the .tt?

**Comment by sjh37** [comment]
Hi @tss56 

`Settings.ConnectionString` is mandatory in version 3. It is used by the generator to read your database schema. It's also placed into the generated code:

## Code 1
```c#
var OnConfigurationUsesConfiguration    = Settings.OnConfiguration == OnConfiguration.Configuration;
var OnConfigurationUsesConnectionString = Settings.OnConfiguration == OnConfiguration.ConnectionString;

{{#if OnConfigurationUsesConfiguration}}
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder){{#newline}}
    {{{#newline}}
        if (!optionsBuilder.IsConfigured && _configuration != null){{#newline}}
        {{{#newline}}
            optionsBuilder.UseSqlServer(_configuration.GetConnectionString(@""{{ConnectionStringName}}""){{ConnectionStringActions}});{{#newline}}
        }{{#newline}}
    }{{#newline}}{{#newline}}
{{/if}}

{{#if OnConfigurationUsesConnectionString}}
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder){{#newline}}
    {{{#newline}}
        if (!optionsBuilder.IsConfigured){{#newline}}
        {{{#newline}}
            optionsBuilder.UseSqlServer(@""{{ConnectionString}}""{{ConnectionStringActions}});{{#newline}}
        }{{#newline}}
    }{{#newline}}{{#newline}}
{{/if}}
```

`Settings.ConnectionStringName` is not used by the generator, but is placed into the generated DbContext constructor via a call to `Settings.DefaultConstructorArgument`.

Code 1 is controlled by `Settings.OnConfiguration`. The values for this enum are `OnConfiguration.Configuration`, `OnConfiguration.ConnectionString`, `OnConfiguration.Omit`. The default is `Settings.OnConfiguration = OnConfiguration.ConnectionString`

## Code 2
```c#
var HasDefaultConstructorArgument = !string.IsNullOrEmpty(Settings.DefaultConstructorArgument);
var AddParameterlessConstructorToDbContext = Settings.AddParameterlessConstructorToDbContext;

{{#if AddParameterlessConstructorToDbContext}}
    /// <inheritdoc />{{#newline}}
    public {{DbContextName}}(){{#newline}}
{{#if HasDefaultConstructorArgument}}
        : base({{DefaultConstructorArgument}}){{#newline}}
{{/if}}
    {{{#newline}}
{{#if DbContextClassIsPartial}}
        InitializePartial();{{#newline}}
{{/if}}
    }{{#newline}}{{#newline}}
{{/if}}
```
Code 2 is added/removed by setting `Settings.AddParameterlessConstructorToDbContext` to true or false.

**Comment by ClassyCircuit** [comment]
@sjh37 I have the same issue and I don't really understand the answer. 
How can we specify in .tt generator files to use the connection string that is inside app.config? To avoid hard coding the actual connection string inside every .tt file. 
You said it is not used by the generator - what does that mean? If I don't hard code the connection string, then it won't generate the entities?
Also, does the app.config file need to be physically inside the same project, or can it be a shared config file on the solution level?
Thanks

**Comment by sjh37** [comment]
Hi @janissimsons 
Version 2 of the generator used to search for your connection string by searching through app.config, web.config, etc.
Version 2 also relied on functions within `EF6.Utility.CS.ttinclude` to perform this project iteration within Visual Studio. All the files within a project are listed for .net 4.x projects.

This is not true for .Net Core projects. The project file does not list the files to be used within the project, as all files within the folder are used. Hence version 3 makes used of `EF6.Utility.CS.ttinclude`  for .Net 4.x projects, but not not for .Net Core projects as this would not work.

In order to read appsettings.json, which is in JSON, the generator is a T4 template, and cannot include NuGet packages such as JSON.NET. T4 templates are ran when you press save. JSON parsing code would have to be either included within the generator, or within a standard system namespace. This functionality is provided in .Net 5.0 and .Net Core 3.1, but not .Net 4.x.

To get something common and simple for both .Net 4.x and .Net Core project types, you specify the connection string in the tt file to use for reverse engineering.

If you did want the generator to search your config files for a connection string, which file should be used if the connection string exists in multiple json and xml files within your solution?

- appsettings.json
- appsettings.development.json
- appsettings.staging.json
- appsettings.production.json
- web.config
- app.config

You need something consistent across many different developer configurations and solutions. Specifying the connection string in the generator tt file covers both scenarios of reading and parsing JSON and XML files, and solves the problem of picking the right one. It also gives you the ability to have a different connection string in your code, from what is used for reverse generation. Hence it was the simplest and most versatile solution.

**Comment by ClassyCircuit** [comment]
@sjh37 Thanks for the detailed explanation!
My problem is that I have different database environments, so when I switch to a different environment, I want to re-generate all my .tt files, but I can't really do that, because connection string is hard-coded in the .tt file.

Is there some alternative way, where I could gather up all the connection strings for different environments, and then regenerate .tt based on that?
In version 2 it was quite easy - I could change the connection string in one place and then I could regenerate the entities.

**Comment by sjh37** [comment]
Hi @janissimsons
Can you elaborate a little more on your different database environments, and how you relate the generator to your different database environments. It might help me fully understand your setup.

It could be you have many different solutions, and many reverse generator projects within each solution. For example
```
Project 1
    Data folder
        claims.tt - insurance db filtered to claims
Project 2
    Data folder
        sales.tt - insurance db filtered to sales
Project 3
    Data folder
        warehouse.tt - warehouse db filtered to customers, sales, pending orders
```
The above for project 1 & 2 would have the same connection string, but project 3 would have a different connection string.

**Comment by ClassyCircuit** [comment]
@sjh37 
I have two projects within the same solution that have these generators, one project has entities and interfaces, the other has contexts and configurations.

```
Core.Domain:
    Entities:
        Generator1.tt
        Generator2.tt
        Generator3.tt
Core.Infrastructure:
    Data:
        Generator1.tt
        Generator2.tt
        Generator3.tt
```

I have two test environments, where a separate solution deploys the latest changes to DB (I am not in control of DB development, a different team is doing, I just have to use the DBs they develop to run all sorts of verifications).

**Environment1** has master branch deployed there, which usually is 2-3 weeks behind of latest development, meaning it has a slightly different DB structure than **Environment2**, which holds the latest changes.

I have to test both environments, meaning I have to maintain two branches in my solution - one for testing **Environment1** and the other for **Environment2**.

Since I have a lot of these reverse generators (currently 15 databases, each has around ~50 tables), I need to regenerate them automatically whenever there is a new deployment to one of the environments, but I have to reverse engineer from the correct environment.

I have two appsettings files, which hold the connection strings:
appsettings.environment1.json
appsettings.environment2.json

```JSON
{
  "AppSettings": {
    "ConnectionStrings": {
      "Source": {
        "DB1": "Server=<sql_server_conn>",
        "DB2": "Server=<sql_server_conn>",
        "DB3": "Server=<sql_server_conn>"
      }
    }
  }
}

```
Ideally, I want a single command that reads in the correct connection strings from configuration file and then uses them to regenerate all generators.
Also, I would like to use the same config file whenever I am connecting to these DBs with entity framework.


Yesterday, I came up with a solution to my problem - I created a console app that does the following:
1) Reads the correct appsettings file (based on which GIT branch I am currently on, if it's master, then we take Environment1, otherwise we take Environment2 settings.
2) Binds it to a strongly-typed C# object.
3) Creates a simple `.ttinclude` file, which holds string variables that point to connection strings and populates those variables from the previously binded appsettings file.
```c#
<#
#pragma warning disable CS0219
// This is automatically generated file. 
string DB1 = @"<connection taken from appsettings file>";
string DB2 = @"<connection taken from appsettings file>";
string DB3 = @"<connection taken from appsettings file>";
#>
```
4) All the generators include this `.ttinclude` file and are set to use their respective variables as the connection string.
5) Then the app finds all .tt generators inside both projects, gets their full path and namespace.
6) Then for each .tt generator it starts a new process that calls the `TextTransform.exe`, eventually regenerating all .tt generators inside the solution, like this:

```c#
private void RunInParallel(List<EntityPath> entityPaths, string textTransformTool, string designDLL)
{
    Parallel.ForEach(
        entityPaths,
        new ParallelOptions { MaxDegreeOfParallelism = Convert.ToInt32(Math.Ceiling((Environment.ProcessorCount * 0.75) * 1.0)) },
        entity =>
    {
        var process = new Process
        {
            StartInfo =
            {
                FileName = textTransformTool,
                Arguments = $@"{entity.FilePath} -dp T4VSHost!Microsoft.Data.Entity.Design.VisualStudio.Directives.FallbackT4VSHostProcessor!""{designDLL}"" -a !!namespaceHint!""{entity.FileNamespace}"""
            }
        };

        process.Start();
        process.WaitForExit();
        Console.WriteLine($"Regenerated: {entity.FilePath} in namespace: '{entity.FileNamespace}'");
    });
}
```

It was very difficult to get the TextTransform.exe tool to work properly, I can't copy it from Visual Studio installation location to my solution (in case I want to use it on a machine that doesn't have VS installed), because it has a bunch of dependencies that I can't find.
Also, if I don't pass in namespaceHint parameter, then it regenerates all entities in the `DebugMode` namespace, and finding those namespaces from filenames isn't easy, so I reverted to holding all related generators in the same namespace and just hardcoding the needed namespace for entities and the other for contexts.

I am not certain this is the best approach, but this is what I could come up with in a couple of hours.
Do you have some suggestions, maybe I don't need to call the TextTransform tool directly and there is an alternative way?

Thanks!

**Comment by sjh37** [comment]
@janissimsons That is genius!
I think this is a great solution, and it executes in parallel too.
I also have future plans to also make the generator into a dotnet.exe extension. #610 That will allow you to generate from the command line, or a console application.
