### ISSUE TITLE
Modifying StoreProcedureReturnTypes keeps ResultSets 

### ISSUE THREAD

**Issue by tss56** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#626]
Hi! 
I'm trying to change the return type for my stored procedure because I don't want to use the ReturnModel but just entity, so I added my store procedure and the entity through StoreProcedureReturnTypes but in the Context generated I still have some [Entity].ResultSet.., which are of course not defined in my Entity, is it normal ? or did I miss something?
Also, I don't really know what is the use of ReturnModels ? How can it be used to get an entity if that's possible?
Thanks

**Comment by sjh37** [comment]
Hi @tss56 
I guess you are seeing multiple result sets like this:
```sql
public class StpMultipleResultsReturnModel
{
    public class ResultSetModel1
    {
        public int codeObjectNo { get; set; }
        public int? applicationNo { get; set; }
    }
    public List<ResultSetModel1> ResultSet1;

    public class ResultSetModel2
    {
        public int cogID { get; set; }
        public string cogCompanyGroupName { get; set; }
        public DateTime? cogValidFrom { get; set; }
        public DateTime? cogValidTo { get; set; }
    }
    public List<ResultSetModel2> ResultSet2;

    public class ResultSetModel3
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    public List<ResultSetModel3> ResultSet3;
}
```

That will be because the stored procedure can return multiple result sets. This example above was created from:
```sql
CREATE PROCEDURE [dbo].[stp_multiple_results]
AS
	SELECT  [codeObjectNo], [applicationNo] FROM [dbo].[CodeObject];
	SELECT * FROM CompanyGroup;
	SELECT * FROM Colour;
GO
```
If a stored procedure contains conditional statements, such as this:

``` sql
IF(@someVar < @otherVar) BEGIN
   SELECT a,b,c WHERE blah
ELSE
   SELECT a,b,c WHERE blah OR blah
END
```

The result sets will be the same, even though two can be returned.
Instead of including ResultSet1 and ResultSet2, these can be merged and instead use a single return model.
See cases #265 and #37

**Comment by sjh37** [comment]
I will close this as its a duplicate

**Comment by tss56** [comment]
Thank for your reply
No, actually I don't have the [stp]ReturnModel class because I defined this [stp] to return an entity,
what I have is that in my [stp] generated definition (in the context file because I separate them) there is this part:
try
```c#
{
    DbInterception.Dispatch.Connection.Open(Database.Connection, new DbInterceptionContext());

    var reader = cmd.ExecuteReader();

    var objectContext = ((IObjectContextAdapter) this).ObjectContext;
    procResultData.**ResultSet1** = objectContext.Translate<CBobbin.**ResultSetModel1**>(reader).ToList();
    reader.NextResult();

    procResultData.**ResultSet2** = objectContext.Translate<CBobbin.**ResultSetModel2**>(reader).ToList();
    reader.NextResult();

    procResultData.**ResultSet3** = objectContext.Translate<CBobbin.**ResultSetModel3**>(reader).ToList();
    reader.Close();
}
```
Or ResultSets and ResultSetModels aren't anywhere else
I think maybe I should explain what I do in my store procedure is all basics CRUDs and some other specifics tasks, I indicate which with a Task number that is then tested for each possible task (IF @Task = ... BEGIN ... END)

**Comment by sjh37** [comment]
Hi @tss56. Because of the way sql server returns its data, you have to carefully match what is returned by stored procedure. In your case, because of the `IF BEGIN END` clauses you get three result sets back. If you only want to use the first one, and ignore the others, you can write a partial db context class (set `Settings.DbContextClassModifiers = "public partial";`) and extend the call to your stored procecture so it calls the EF code above, and simply map the ResultSetModel1 to your entity. AutoMapper would do this automatically for you, or you can simply manually copy the fields across.
