### ISSUE TITLE
Rename Section 

### ISSUE THREAD

**Issue by smarteez17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#630]
HI 
Lines (219 to 241 ) is the table rename section . Here I can and "View" to all view . What I want to try to it group all the entries together so all Views start with View , Stored Proc starts with SP, Tables start with TB , Functions ( Table and scalar ) start with ...

Is this possible? 

Taking this a step further within the entries folder can I split this into sub folders

**Comment by sjh37** [comment]
To rename tables & views, edit `Settings.TableRename` and add
```c#
if(isView)
    name = "View" + name;
else
    name = "Table" + name;
```

In Settings.StoredProcedureRename change the return to be
```c#
if(sp.IsStoredProcedure)
	return "SP" + sp.NameHumanCase;
if(sp.IsScalarValuedFunction)
    return "SVF" + sp.NameHumanCase;
if(sp.IsTableValuedFunction)
    return "TVF" + sp.NameHumanCase;
return sp.NameHumanCase;
```

For sub-folders, you have to create a copy of the generator in each of your sub folders, and specify what elements you want generated in the sub folder by specifying Settings.ElementsToGenerate.
For example in your entities folder, set 
```c#
Settings.ElementsToGenerate = Elements.Poco;
```

**Comment by smarteez17** [comment]
same problem as #631 it does updated only when I delete the old files it works

**Comment by sjh37** [comment]
I will close this issue, as moving from `Settings.GenerateSeparateFiles` from `true` to `false` will not delete your files. I don't want the generator to delete files either if `Settings.GenerateSeparateFiles = false` because there could be scenarios where the user has file names that match the names of classes within the generated `<database>.cs` file, and I don't want to accidentally delete those.
