### ISSUE TITLE
The DbContext of type 'ApplicationDbContext' cannot be pooled because it does not have a public constructor ...

### ISSUE THREAD

**Issue by manu191357** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#657]
Hello,
yesterday I bought a licence and started testing the generator. It works fine, but I am getting

`The DbContext of type 'ApplicationDbContext' cannot be pooled because it does not have a public constructor ...`

unless I comment out

```c#
        public ApplicationDbContext()
        {
        }
```

from my ApplicationDbContext class and also the region

```c#
    public class MyDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            return new ApplicationDbContext();
        }
    }
```

Then the application builds without errors, runs correctly and migration is also working.
I just would like to know, why the commented code pieces are generated, what they are for and what could cause problems if commented out.

Regards, Manu

**Comment by sjh37** [comment]
Hi Manu. Thank for your support!
Take a look at [Stack Overflow](https://stackoverflow.com/q/45804470/5884) as it may be fixed by configuring how the DI container creates the database context.

Also take a look at the following wiki article about OnConfiguration, that may help too.
https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Settings.OnConfiguration

If all else fails, you can always remove the default constructor from being generated by removing this section at approx. line 16170:

```
static {{DbContextName}}(){{#newline}}
{{{#newline}}
    System.Data.Entity.Database.SetInitializer{{setInitializer}}{{#newline}}
}{{#newline}}{{#newline}}
```

line 17655, just make this `DatabaseContextFactory()` return an empty string by changing it to:
```c#
public override string DatabaseContextFactory()
{
    return "";
}
```

**Comment by manu191357** [comment]
Hello,
thank you for your help and explanation. Referring to the link to Stack Overflow: I will stick to commenting out as outlined in my post and keeping AddDbContextPool in the ConfigurationServices such as: 

`            services.AddDbContextPool<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));`

This way, my DbContext class stays small/clean and I can take the benefits of using AddDbContextPool.

Regards, Manu
