### ISSUE TITLE
Computed column attributes

### ISSUE THREAD

**Issue by mrbillo** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#689]
Updated from version 2.36 to 3.30. I'm using EF6. Manually copied settings from old version. UseDataAnnotations is on. It won't generate attributes like [DatabaseGenerated(DatabaseGeneratedOption.Computed)]. The timestamp and identity columns show [Required] but not any computed attributes. Ideas ? Vs2019

**Comment by sjh37** [comment]
Some data annotations were removed in version 3 due to not being able to fully document the schema. Only fluent configurations can fully describe your database schema in Entity Framework.
Some data annotations are still handy though for ASP.NET website views and form part of the data entry validation. The main ones are `Key`, `Timestamp`, `Display name`, `MaxLength`, `StringLength`, and `Required`. You can find these in your `<database>.tt` file within the function `Settings.UpdateColumn`.

The fluent configurations for your class is where you will find the `.HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)` for your computed fields.
