### ISSUE TITLE
Error when exclude Elements.UnitOfWork from ElementsToGenerate

### ISSUE THREAD

**Issue by Kasper888** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#94]
When I try to remove Elements.UnitOfWork from ElementsToGenerate in database.tt then save, the generated MyDbContext would implement IMyDbContext (supposed to not) so i get compile error that IMyDbContext not exists.

**Comment by Kasper888** [comment]
after insepcting the EF.Reverse.POCO.ttinclude, i fixed it by replace line 190 with 
`public <# if(MakeClassesPartial) { #>partial <# } #>class <#=DbContextName#> : <#=DbContextBaseClass#><#if(ElementsToGenerate.HasFlag(Elements.UnitOfWork)){#>, <#=DbContextInterfaceName#><#}#>`

kindly include this fix in the next release...
Thanks in advance

**Comment by sjh37** [comment]
The code is correct, you are using it wrong.
You need to add another folder for interfaces in your data project, and add in the generator again, but only specifying the interfaces element.
The generator will only create the interface.

In your main project, you correctly missed out the interfaces element to generate because you know it will be generated in another folder. So in your main settings tt file, set the following variable to the namespace where your interface is generated.

``` c#
UnitOfWorkNamespace = "";
```

This adds a using statement to your generated db context, and so picks up the interface.

SOLID principles state that you must always code against an interface, and never the actual concrete thing. This is so you can perform unit testing, and swap out the real db context for the generated fake db contexts.

**Comment by sjh37** [comment]
Watch the Pluralsight course to see how this is done in separate folders within the same project, and then I move on to show how to do it in separate projects.

**Comment by Kasper888** [comment]
Thanks for ur advice, I've already watched ur Pluralsight course and it's amazing, it teaches me many ways to gracefully use EF on enterprise level also I'm very happy that u constantly push updates to this project keep it up :+1: 

About the issue, I was just trying to quickly reverse 4 tables to view special relation mapping cases using the minimum lines of generated code, it was no need for unit testing, context interface or projects/folder separation and u put an option to choose only what i want to generate; So i removed the UnitOfWork flag. 

Still see that the tiny additional validation i've added is valid and agree with defensive coding & robustness principle.

**Comment by sjh37** [comment]
:-)
